% Description: generate reference by combining cross-run averaging and a one-sample t-test
% Usage:
%   smm = tRef(St,tcS,mask_ind, alpha, V)
% Input: 
    % St: cross-run averaging spatial maps with dimension 1 x V
    % tcS: t values of one-sample t-test with dimension 1 x V
    % mask_ind: mask for in-brain voxels with dimension 1 x V
    % alpha: a value specifying the significance level as (100*ALPHA)%
    % V: degrees of freedom
% Output: 
    % smm: reference generated by combining cross-run averaging and a one-sample t-test with dimension 1 x V
% Reference: Kuang,L.D., Lin,Q.H., Gong,X.F., Cong,F., Sui,J., & Calhoun,V.D.(2018). 
%            Model order effects on ICA of resting-state complex-valued fMRI data: application to schizophrenia. 
%            Journal of Neuroscience Methods, 304, 24¨C38. 
% Date: May 2017
% Author: Li-Dan Kuang  
%*****************************************************************
function smm = tRef(St,tcS,mask_ind, alpha, V)
    sm1=zeros(1,53*63*46);sm1(mask_ind)=(tcS); 
    sm2=zeros(1,53*63*46);sm2(mask_ind)=(St); 
    inn= find(abs(sm1)>tinv(alpha + (1 - alpha)/2, V)&abs(sm2)>0);
    sm = zeros(1,53*63*46);  sm(inn) = sm2(inn);  
    smm = sm(mask_ind); 
